### PR TITLE
add pre-commit lint hook and audit

### PR DESCRIPTION
**Pull request by amydegenaro**

### CODE REVIEW

**Comment by mincer-ray** [comment]
what does this do

**Comment by amydegenaro** [comment]
it runs npm lint when you try to commit so you don't find out in build stage that you should've fixed something

**Comment by mincer-ray** [comment]
im not totally against it but i feel like it might slow me down at the moment. might put on hold.

also doesnt this make the github action lint redundant?

**Comment by amydegenaro** [comment]
makes sense, it's sorta up to you and depends how you work. I'd rather update linting stuff from the beginning instead of updating the PR after a build fails, but that's just the way I'm used to doing it at work so thought it might help here too. but yeah, really doesn't matter either way though

**Comment by mincer-ray** [comment]
waiting on https://github.com/mincer-ray/botto-kun/pull/29 to take this off hold

**Review by mincer-ray — APPROVED** [review]

**Pull request merged**
